### ISSUE TITLE
L2TP/IPsec connection not working with recent SoftEther VPN Server versions running on Windows XP

### ISSUE THREAD

**Issue by jartester** [SoftEtherVPN/SoftEtherVPN#688]
* [ ] Can you reproduce? -> Yes.
* [ ] Are you running the latest version of SoftEtherVPN? -> Yes, I tried it too but the one that works for me is an earlier version.

**SoftEther version:**
softether-vpnserver_vpnbridge-v4.27-9668-beta-2018.05.29-windows-x86_x64-intel.exe 

**Component:** [Server, Client, Bridge, etc.] ->Server
**Operating system:** [Windows, Linux, BSD, macOS, etc.] -> Windows (XP SP3)
**Architecture:** [64 bit, 32 bit] -> 32 bit

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]

Doesn't matter, tested on very different CPUs and machines.

### Description

[Description of the bug]

**Expected behavior:**
 To accept L2TP/IPSec PSK connections

**Actual behavior:**
[What actually happened]
The negotiation process does not pass

### Steps to reproduce

1. [First step] Install any version *HIGHER* (newer) than "softether-vpnserver_vpnbridge-v4.25-9656-rtm-2018.01.15-windows-x86_x64-intel.exe"
2. [Second step] Try to connect to it from Android device with L2TP/IPSec PSK (no other clients tested). Your attempt will fail. You can dig the exact error from log files on the server side. As far as I remember it was some kind of internal error. 
3. Uninstall current version and Install "softether-vpnserver_vpnbridge-v4.25-9656-rtm-2018.01.15-windows-x86_x64-intel.exe". 

4. Try to connect the same VPN, don't touch the settings at all again and you will succeed.

**Comment by chipitsine** [comment]
can you specify android version, please ?

**Comment by jartester** [comment]
Different devices with 4.1.2 and 4.2.2. I used older versions since they have orange and green flashing arrows that show incoming and outgoing data traffic. I guess the Android version is irrelevant.

**Comment by jartester** [comment]
port number: 1701), connection "CID-3-BF664ABBD3" has been created.
2018-09-04 10:42:45.318 SSL communication for connection "CID-3-BF664ABBD3" has been started. The encryption algorithm name is "(null)".
2018-09-04 10:42:45.348 Connection "CID-3-BF664ABBD3" terminated by the cause "An internal error occurred." (code 23).
2018-09-04 10:42:45.348 Connection "CID-3-BF664ABBD3" has been terminated.

**Comment by jartester** [comment]
davidebeatrici,   the label "os/Android" added by you is wrong, the OS is Windows but since not tested on other OSes the issue most likely could be general. Likewise the client OS also could be irrelevant since not tested with clients under different OSes than Android...

**Comment by davidebeatrici** [comment]
Is the issue present with other versions of Windows?

**Comment by jartester** [comment]
I haven't tested this issue of the SoftEther VPN server in any other OS but windows XP...

**Comment by jartester** [comment]
I've just tried the latest softether server under Windows 10 x64 and it worked as it should. It is highly likely the problem is related either to Windows XP x86 or (not tested so far) to 32-bit Windows OSes...

**Comment by davidebeatrici** [comment]
#294 added SHA-256, SHA-384, and SHA-512 support to the protocol, but part of it was removed in faee11ff096e7950b006ef1ae8dc636b6fe0131e, presumably because it broke C89 compatibility.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/8fdd224ba7f5676f99d74c7c63f60e046d07ec97/src/Cedar/Proto_IkePacket.c#L3003-L3014

**Comment by davidebeatrici** [comment]
This issue is only present in official signed builds and it's not fixed by #694.

According to @dnobori, builds after 9656 are signed with a different certificate.

**Comment by dnobori** [comment]
I found the cause. This problem causes only on Authenticode-signed binaries. I changed Authenticode certificate from DigiCert SHA-256 & SHA-1 to Codomo SHA-256 only. It fails on Windows XP. I am going to fix the build as soon as possible.

**Comment by jartester** [comment]
@dnobori
Thank you.

**Comment by dnobori** [comment]
I published the new binary (Build 9669) with SHA-1 and SHA-256 dual Authenticode digital certificates.
https://www.softether.org/5-download/history

Could you please try it?

**Comment by jartester** [comment]
Sorry, but the problem still remains the same with "softether-vpnserver_vpnbridge-v4.28-9669-beta-2018.09.11-windows-x86_x64-intel.exe".

**Comment by jartester** [comment]
It works. Thank you.

**Comment by lazmo88** [comment]
Having exactly the same issue with the latest build. Android 9 and host is Windows 10. Works fine when using the SE client, but builtin Windows client fails to connect. Same goes with Android 9 handset.
